# Service tipe ClusterIP supaya backend bisa akses Mongo lewat DNS name
# yang stabil, "mongo" (dipakai langsung sebagai MONGO_HOST di API karsajobs).
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: karsajobs
  labels:
    app: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo
